osx_image: xcode6.4
language: objective-c
xcode_sdk: 
	-iphonesimulator8.4
	-iphonesimulator7.1

xcode_workspace: Examples/ADAppRater Demo/ADAppRater Demo.xcworkspace
xcode_scheme: 'ADAppRater Demo'
podfile: Examples/ADAppRater Demo/Podfile

