osx_image: xcode7.2
language: objective-c

podfile: Podfile
cache: cocoapods

xcode_workspace: ADAppRater.xcworkspace
xcode_scheme: 'ADAppRater'
xcode_sdk:
    - iphonesimulator9.2
    - iphonesimulator8.2
    - iphonesimulator7.1

#env:
 # matrix:
  #  - xcode_sdk: iphonesimulator9.2
#    - xcode_sdk: iphonesimulator8.2
#    - xcode_sdk: iphonesimulator7.1

#script:
#  - xctool test -test-sdk $TEST_SDK -simulator $SIMULATOR

