language: objective-c

podfile: Podfile
cache: cocoapods

xcode_workspace: ADAppRater.xcworkspace
xcode_scheme: 'ADAppRater'

env:
  matrix:
    - osx_image: xcode7.2, xcode_sdk: iphonesimulator9.2
    - osx_image: xcode6.4, xcode_sdk: iphonesimulator8.4
    - osx_image: xcode6.1, xcode_sdk: iphonesimulator7.1

#script:
#  - xctool test -test-sdk $TEST_SDK -simulator $SIMULATOR

